CREATE TABLE APPLICANT_DECISION (
    ID INTEGER NOT NULL UNIQUE,
    APPLICANT_FINAL_DECISION VARCHAR(150) NOT NULL,
    APPLICANT_SYSTEM_ID VARCHAR(150) NOT NULL,
    SENT VARCHAR(50) NOT NULL,
    DECISION_MADE_AT DATE NOT NULL,
    FLOW_UNIQUE_ID VARCHAR(150) NOT NULL UNIQUE,
    PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX IDX_APPLICANT_SYSTEM_ID ON APPLICANT_DECISION(APPLICANT_SYSTEM_ID);

COMMENT ON TABLE APPLICANT_DECISION IS 'table for applicant final decision';