server:
  port: 8082

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'

  zipkin.tracing.endpoint: 'http://localhost:9411/api/v2/spans'

logging.pattern.level: '%5p [application-name: ${spring.application.name:}, traceId: %X{traceId:-}, spanId: %X{spanId:-}]'

spring:
  liquibase:
    change-log: 'classpath:db/changelog/changelog-initial-checks.yaml'
  application:
    name: initial-checks
  datasource:
    username: 'sleeplesschallenger'
    password: 'superSecret'
    url: jdbc:postgresql://localhost:5435/initial-checks-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: 'http://localhost:9411'
  rabbitmq:
    addresses: 'localhost:5672'

app:
  executor:
    threadsPerProcessor: 10

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    applicant-models: applicant.queue
    deposit-models: deposit.queue
  routing-keys:
    internal-applicant: internal.applicant.routing-key
    internal-deposit: internal.deposit.routing-key

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true