server:
  port: 8082

spring:
  application:
    name: initial-checks
  datasource:
    username: 'sleeplesschallenger'
    password: 'superSecret'
    url: jdbc:postgresql://localhost:5435/initial-checks-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

app:
  executor:
    threadsPerProcessor: 10

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true