CREATE TABLE IF NOT EXISTS CHECK_APPLICATION (
    ID INTEGER NOT NULL UNIQUE,
    APPLICANT_ID VARCHAR(150) NOT NULL,
    DEPOSIT_ID VARCHAR(150) NOT NULL,
    CREATED_AT DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX IDX_APPLICANT_ID ON CHECK_APPLICATION(APPLICANT_ID);
CREATE UNIQUE INDEX IDX_DEPOSIT_ID ON CHECK_APPLICATION(DEPOSIT_ID);

COMMENT ON TABLE CHECK_APPLICATION IS 'table of applicant and deposit system ids to keep their flow in the system';