services:
  postgres-checks:
    container_name: postgres-initial-checks
    image: postgres
    environment:
      POSTGRES_USER: sleeplesschallenger
      POSTGRES_PASSWORD: superSecret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres-scoring
    restart: unless-stopped
  postgres-start:
    container_name: postgres-start-scoring
    image: postgres
    environment:
      POSTGRES_USER: sleeplesschallenger
      POSTGRES_PASSWORD: superSecret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres-scoring
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin-start-scoring
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres-scoring
    restart: unless-stopped
  zipkin:
    container_name: zipkin-tracing
    image: openzipkin/zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres-scoring:
    driver: bridge

volumes:
  postgres:
  pgadmin: