spring:
  application:
    name: api-gateway
  zipkin:
    base-url: 'http://localhost:9411'
  cloud:
    gateway:
      routes:
        - id: start-scoring
          uri: lb://START-SCORING # name from Eureka server
          predicates:
            - Path=/api/v1/startScoring/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true