spring:
  application:
    name: api-gateway
  zipkin:
    base-url: 'http://zipkin-tracing:9411'
    # TODO: for now we use container name. Later - use Labels for ConfigMaps in K8S
  cloud:
    gateway:
      routes:
        - id: start-scoring
          uri: lb://START-SCORING # name from Eureka server
          predicates:
            - Path=/api/v1/startScoring/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: 'http://eureka-server:8761/eureka'
    fetch-registry: true
    register-with-eureka: true