CREATE TABLE APPLICANTS (
    ID INTEGER NOT NULL UNIQUE,
    APPLICANT_SYSTEM_ID VARCHAR(150) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    MIDDLE_NAME VARCHAR(100),
    AGE INTEGER NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX IDX_APPLICANT_SYSTEM_ID ON APPLICANTS(APPLICANT_SYSTEM_ID);

COMMENT ON TABLE APPLICANTS IS 'table of applicant';