CREATE TABLE IF NOT EXISTS DEPOSITS (
    ID INTEGER NOT NULL UNIQUE,
    DEPOSIT_SYSTEM_ID VARCHAR(150) NOT NULL,
    DEPOSIT_TYPE VARCHAR(100) NOT NULL,
    DEPOSIT_PRICE NUMERIC NOT NULL,
    DEPOSIT_AGE INTEGER NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE NOT NULL,
    APPLICANT_ID INTEGER NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_APPLICANT
        FOREIGN KEY (APPLICANT_ID)
            REFERENCES APPLICANTS (ID)
);

CREATE UNIQUE INDEX IDX_DEPOSIT_SYSTEM_ID ON DEPOSITS(DEPOSIT_SYSTEM_ID);

COMMENT ON TABLE DEPOSITS IS 'table of deposit';