server:
  port: 8085

management:
  tracing:
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://zipkin-tracing:9411/api/v2/spans}

logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: ${KAFKA_TOPIC:deposit-topic}
  application:
    name: deposit-models
  rabbitmq:
    addresses: ${RABBIT_MQ:rabbitmq:5672}

rabbitmq:
  exchanges:
    internal: ${RABBIT_MQ_EXCHANGE:internal.exchange}
  queues:
    deposit-models: ${RABBIT_MQ_APPLICANT_QUEUE:deposit.queue}
  routing-keys:
    internal-deposit: ${RABBIT_MQ_RK_APPLICANT:internal.deposit.routing-key}

# in routing-keys: name_of_the_exchange.queue_name.routing-key

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ENDPOINT:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true