server:
  port: 8085

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'

  zipkin.tracing.endpoint: 'http://localhost:9411/api/v2/spans'

logging.pattern.level: '%5p [application-name: ${spring.application.name:}, traceId: %X{traceId:-}, spanId: %X{spanId:-}]'

spring:
  kafka:
    bootstrap-servers: 'localhost:29092'
    topic: 'deposit-topic'
  application:
    name: deposit-models
  rabbitmq:
    addresses: 'localhost:5672'

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    deposit-models: deposit.queue
  routing-keys:
    internal-deposit: internal.deposit.routing-key

# in routing-keys: name_of_the_exchange.queue_name.routing-key

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true