server:
  port: 8085

management:
  tracing:
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: 'http://localhost:9411/api/v2/spans'

logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"

spring:
  kafka:
    bootstrap-servers: 'localhost:9092'
  application:
    name: deposit-models
  rabbitmq:
    addresses: 'localhost:5672' # TODO: put label to apply in K8S further

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    deposit-models: deposit.queue
  routing-keys:
    internal-deposit: internal.deposit.routing-key

# in routing-keys: name_of_the_exchange.queue_name.routing-key

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true