spring:
  application:
    name: eureka-server

management:
  tracing:
    enabled: false

server:
  port: 8761
eureka:
  client:
    fetch-registry: false
# it is to prevent this microservice to register itself in the eureka server