server:
  port: 8081

spring:
  application:
    name: start-scoring
  datasource:
    username: 'sleeplesschallenger'
    password: 'superSecret'
    url: jdbc:postgresql://localhost:5434/postgres-start-scoring-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true