server:
  port: 8084

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'

  zipkin.tracing.endpoint: 'http://localhost:9411/api/v2/spans'

logging.pattern.level: '%5p [application-name: ${spring.application.name:}, traceId: %X{traceId:-}, spanId: %X{spanId:-}]'

spring:
  kafka:
    bootstrap-servers: 'localhost:29092'
    topic: "applicant-topic"
  application:
    name: applicant-models
  rabbitmq:
    addresses: 'localhost:5672'
#    listener:
#      simple:
#        retry:
#          enabled: 'true'
#          initial-interval: 3s
#          max-attempts: 3
#          max-interval: 7s
#          multiplier: 2

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    applicant-models: applicant.queue
  routing-keys:
    internal-applicant: internal.applicant.routing-key

# in routing-keys: name_of_the_exchange.queue_name.routing-key

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
    fetch-registry: true
    register-with-eureka: true